version=2.0.3-fabric.1.21.10-port
mod_version=2.0.3-fabric.1.21.10-port
group=dev.ryanhcode.sable
mod_name=Sable
mod_author=RyanHCode
mod_id=sable
license=PolyForm Shield License 1.0.0
description=Interactive moving block structures with physics, ported for Fabric 1.21.10.
issues=https://github.com/ryanhcode/sable/issues
