plugins {
    id 'java-library'
    id 'net.fabricmc.fabric-loom-remap'
}

apply from: rootProject.file('gradle/fabric-module.gradle')

configurations.configureEach {
    resolutionStrategy.capabilitiesResolution.withCapability('org.lz4:lz4-java') {
        select('at.yawk.lz4:lz4-java:1.11.0')
    }
}

dependencies {
    implementation project(path: ':sable', configuration: 'namedElements')
    implementation project(path: ':simulated', configuration: 'namedElements')
    implementation project(path: ':offroad', configuration: 'namedElements')
}

apply from: rootProject.file('gradle/ponder-gametest.gradle')
